### ISSUE TITLE
Panoptes_aggregation_gui error 

### ISSUE THREAD

**Issue by rpmady** [zooniverse/aggregation-for-caesar#101]
Hello, 

I am trying to use this great tool on a Windows laptop. I have been able to successfully run the panoptes_aggregation_gui from the Command Prompt, see below. 

![cmdprompt](https://user-images.githubusercontent.com/42630011/49465561-ed82e380-f7cb-11e8-8582-b6b66fbfbfc8.JPG)

However, when I fill in the information and click start, I get this screen:
![error](https://user-images.githubusercontent.com/42630011/49465582-f5428800-f7cb-11e8-9dd8-8b91a1deedc0.JPG)

I'm not sure what I am doing wrong since the file does exist. 
![image](https://user-images.githubusercontent.com/42630011/49465642-17d4a100-f7cc-11e8-910a-c6504c2b13b6.png)

Any help would be greatly appreciated!

**Comment by CKrawczyk** [comment]
Duplicate to #100 (see that issue for a fix).  In the long run I will look into a post-install script to make the link automatically.

**Comment by rpmady** [comment]
Thank you, thank you!
