### ISSUE TITLE
Adding in custom effects from caesar?

### ISSUE THREAD

**Issue by camallen** [zooniverse/aggregation-for-caesar#116]
Caesar has the data flow of extract -> reduce -> rules -> effect and while there are some internal ones custom code for the extractors, reducers and effects can be externally hosted (please correct).

This aggregation code base provides the ability to handle custom external reducers / extractors for caesars external extractors and reducers. Can this code base support external effects as well? 

Specifically the use case if the one describe here, https://github.com/zooniverse/front-end-monorepo/issues/455#issuecomment-463684490

Ideally we could host a custom external effect that takes the external effect payload from caesar that adds the custom data from the Zooniverse API  and then forwards to MAST. Thoughts?

**Comment by CKrawczyk** [comment]
Yes, with a bit of set up effects could be added as a new endpoint.  To do this:

- Add a new folder `effects` to the module
- Make an `effects_wrapper.py` file similar to the `extracts_wrapper.py` file (this will make sure the correct fields are passed along from the API to the function)
- Make an `__init__.py` file that holds an dictionary `effects` with the desired API endpoint as the key and the function(s) as values
- Update the `routes.py` file to make the new endpoints (see https://github.com/zooniverse/aggregation-for-caesar/blob/master/routes.py#L63-L68 for an example)

I am doing a similar thing for the TESS user reducer right now in PR #103 if you want a working example (new API endpoint is `running_reducers`).

**Comment by zwolf** [comment]
Doing this on the aggregation service instead of Caesar seems to just bump up the number of total requests required to get the same info. As I mentioned in the monorepo issue, I can build the Panoptes req directly into Caesar's external effect, fire it conditionally based on some config. It doesn't seem like we need the aggregation stack to do this for Caesar unless there's a reason we don't want Caesar and Panoptes conspiring with one another.

**Comment by camallen** [comment]
The idea to locate this functionality here is where the custom behaviour is defined. I can see the behaviour in ceasar generalizing over time and instead of coding in each specific type into caesar we could instead provide the same solutions via custom effects here / external effects in caesar.

Knowing what is achievable was the point of this issue to inform which way we choose to build the feature.

**Comment by zwolf** [comment]
We are going to write an additional method on `aggregation-for-caesar` that will receive the reductions from the `ExternalExtractor` and pull `login` and `credited_name` from Panoptes for each `user_id` present. It will be responsible for forwarding these reductions on to MAST.

_Originally posted by @amyrebecca in https://github.com/zooniverse/caesar/issues/630#issuecomment-467104149_

**Comment by amyrebecca** [comment]
This has been resolved in a prior pull request (#133)
