### ISSUE TITLE
AssertionError: View function mapping is overwriting an existing endpoint function: question_reducer

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/aggregation-for-caesar#128]
This is failing on start:

```python
Traceback (most recent call last):
  File "routes.py", line 65, in <module>
    application.route('/reducers/{0}'.format(route), methods=['POST', 'GET'])(request_wrapper(route)(route_function))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: question_reducer
```

**Comment by amyrebecca** [comment]
This seems to be because `question_reducer` and `survey_reducer` both route to the same function, although I don't quite understand why that should be a problem.

This may be related?

https://stackoverflow.com/questions/19964079/flask-function-mapping-is-overwriting-an-existing-endpoint-function

**Comment by zwolf** [comment]
Pinging @CKrawczyk to make sure it's seen. Doubling up the URLs on a route like this

https://gist.github.com/commadelimited/d78432b9df940b0bdae2

is possible, but the way they're being generated seems to be causing the collision.

**Comment by CKrawczyk** [comment]
Thanks for catching this, I guess pointing two routes to the same function does not work like I thought it would.

It looks like it can be fixed with and `@wraps(func_name)` call (similar to https://github.com/zooniverse/aggregation-for-caesar/blob/master/panoptes_aggregation/extractors/extractor_wrapper.py#L17)
