### ISSUE TITLE
Error in TESS reducer when relevant reduction not included

### ISSUE THREAD

**Issue by zwolf** [zooniverse/aggregation-for-caesar#136]
The `tess_reducer_column` reducer will throw the following error if `"relevant_reduction": null` in an extract:

```
TypeError: 'NoneType' object is not subscriptable
File "/usr/local/lib/python3.6/site-packages/panoptes_aggregation/reducers/tess_reducer_column.py", line 89, in <listcomp>
skill = np.array([rr['data']['skill'] for rr in relevant_reduction])
```

This null value is expected if a user has just started classifying and either hasn't had a training subject classification get reduced and their skill level yet calculated. A couple things could happen here. Either

a) don't attempt a new calc, just return the old data
or
b) we add a feature to Caesar that checks for a specific return status code that would result in a no-op reduction pass without suggesting to Stoplight that the reducer is broken.

**Comment by CKrawczyk** [comment]
I will put in a default value, I think defaulting to a skill of `1` makes sense for this (act as if it was unweighted).
