### ISSUE TITLE
TESS reduction fails with KeyError: "weighted_counts"

### ISSUE THREAD

**Issue by zwolf** [zooniverse/aggregation-for-caesar#138]
When throwing an array of extract(s) at the TESS subject reducer, a KeyError is returned for the "weighted_counts" bit of the cluster. There's a default for that value being set in the main loop. If anything, it seems like it should be the potential `max([])` that would cause a ValueError.

The reduction pass fails in caesar, but I used mockable to get the payload and tested it against the API directly. I'm pretty sure that this request should succeed and return the data in the shape specified in the reducer file, but if there's a problem with the request, please let me know.

Below is the error, followed by the request payload.

error:
```File "/usr/local/lib/python3.6/site-packages/panoptes_aggregation/reducers/reducer_wrapper.py", line 53, in wrapper
reduction = func(data, **kwargs_data, **kwargs_details, **kwargs_extra_data)
File "/usr/local/lib/python3.6/site-packages/panoptes_aggregation/reducers/tess_reducer_column.py", line 114, in tess_reducer_column
                k_skill = [skill[j] for j in index[idx]]
                clusters.setdefault('weighted_counts', []).append(float(sum(k_skill)))
                # user_ids in the cluster
                k_users = [user_id[j] for j in index[idx]]
                clusters.setdefault('user_ids', []).append(k_users)
    clusters['max_weighted_count'] = max(clusters['weighted_counts'])
    return clusters
KeyError: 'weighted_counts'
```
payload:
```
[
  {
    "id": 4895,
    "classification_id": 98846,
    "classification_at": "2019-04-01T21:02:30.460Z",
    "extractor_key": "shape_extractor",
    "workflow_id": 3317,
    "user_id": 1325837,
    "subject_id": 81374,
    "data": {
      "frame0": {
        "T1_tool0_x": [
          13.53072167710528
        ],
        "T1_tool0_width": [
          1.9493203386010904
        ]
      },
      "aggregation_version": "3.0.0"
    },
    "created_at": "2019-04-01T21:02:32.345Z",
    "updated_at": "2019-04-01T21:02:32.345Z",
    "project_id": 1862,
    "relevant_reduction": null
  }
]
```

**Comment by amyrebecca** [comment]
we added this to try to pull out the largest weighted count, but it looks like maybe the code doesn't work if there are no clusters found? i'm not sure. are weighted counts allowed to go below zero, or could i just do something cheesy like

```python
    clusters['max_weighted_count'] = max([0] + clusters['weighted_counts'])
```

**Comment by CKrawczyk** [comment]
It might be best to check if `weighted_counts` exists first, and don't append `max_weighted_count` if it does not (or give it a value of `None` if the key is needed):

```python
if `weighted_counts` in clusters:
    clusters['max_weighted_count'] = max(clusters['weighted_counts'])
else:
    clusters['max_weighted_count'] = None
```
