### ISSUE TITLE
Deploy flask app with a production ready WSGI server

### ISSUE THREAD

**Issue by camallen** [zooniverse/aggregation-for-caesar#165]
It looks like we aren't following recommended practice for deploying our aggregation for caesar flask app
http://flask.pocoo.org/docs/1.0/tutorial/deploy/#run-with-a-production-server

>When running publicly rather than in development, you should not use the built-in development server (flask run). The development server is provided by Werkzeug for convenience, but is not designed to be particularly efficient, stable, or secure.

> Instead, use a production WSGI server. For example, to use Waitress, first install it in the virtual environment:

https://github.com/zooniverse/aggregation-for-caesar/blob/b6b7ee416ed2fe9440ec5365394df817834e0463/panoptes_aggregation/routes.py#L87

**Comment by adammcmaster** [comment]
For consistency I'd suggest [Gunicorn](https://gunicorn.org) since we're using that for our Django apps.
