### ISSUE TITLE
Add `minimum_views` as a prameter to text reducers

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/aggregation-for-caesar#259]
# Option 1

This value sets a new value for each line that tracks if the `minimum_views` has been reached (`minimum_views_reached` seems like a good key name).  This value can be used in combination with `low_consensus` to determine if the front-end transcriber tool should "grey out" a line.

A line should be grey (i.e. not allow any new transcriptions to be made) if `reduction.frameX[Y].low_consensus == False` or `reduction.frameX[Y].minimum_views_reached == True`.

# Option 2

The `minimum_views` keyword can be set on the reducer and the front-end can read the value from the `parameters` section of the reduction. The reducer itself will not use this keyword and no new values will be added to the line reductions.

A line should be grey if `reduction.frameX[Y].low_consensus == False` or `reduction.frameX[Y].number_view >= reduction.parameters.minimum_views`.

# What option is better?
Option 2 is the easier to code as it would not change the reduction structure and calculates no new values, but Option 1 would make it so the front-end does not need to do any additional calculations.

**Comment by CKrawczyk** [comment]
@eatyourgreens what is your opinion on the options above?

**Comment by eatyourgreens** [comment]
I think either will work. At the moment, I'm checking `parameters.minimum_views` in https://github.com/zooniverse/front-end-monorepo/pull/1520.

**Comment by eatyourgreens** [comment]
See https://github.com/zooniverse/front-end-monorepo/pull/1520/commits/f3a20f2fd0f750ad66e51b71c66857f5187cec50
