### ISSUE TITLE
Text aggregation running into issues with numeric values

### ISSUE THREAD

**Issue by mclenard** [zooniverse/aggregation-for-caesar#265]
Hello! I am using the aggregation scripts for a project which involves transcribing page numbers. So, the data for that particular task is either blank or numeric (i.e. a 1-to-5 digit number). When I try to reduce, it both has issues with blank cells (which may well be unavoidable, I'm not sure, I used OpenRefine to populate blank cells with something) but more importantly seems to be taking issue with numeric values. It gives me an error when it attempts to use a .strip() method on the values, saying that int and float values don't have string methods. Clearly! But I really just need those numbers as character/string values, not as numbers. Is there a way to avoid the issue of having the scripts think numeric text task data is int/float? Thanks!

Here is the full error message:
```
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\panoptes_aggregation.exe\__main__.py", line 7, in <module>
  File "c:\python\lib\site-packages\panoptes_aggregation\scripts\aggregation_parser.py", line 295, in main
    cpu_count=args.cpu_count
  File "c:\python\lib\site-packages\panoptes_aggregation\scripts\reduce_panoptes_csv.py", line 197, in reduce_csv
    **apply_keywords
  File "c:\python\lib\site-packages\panoptes_aggregation\scripts\reduce_panoptes_csv.py", line 58, in reduce_subject
    reduction = reducers.reducers[reducer_name](data, user_id=user_ids, **keywords)
  File "c:\python\lib\site-packages\panoptes_aggregation\reducers\reducer_wrapper.py", line 51, in wrapper
    data = process_data(data_in, **kwargs_process)
  File "c:\python\lib\site-packages\panoptes_aggregation\reducers\text_reducer.py", line 18, in process_data
    return [d['text'] for d in data_list if d['text'].strip() != '']
  File "c:\python\lib\site-packages\panoptes_aggregation\reducers\text_reducer.py", line 18, in <listcomp>
    return [d['text'] for d in data_list if d['text'].strip() != '']
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by CKrawczyk** [comment]
For transcription data the code is expecting a string.  If it is passed in as `"5"` rather than `5` it should work.  If it is blank passing in an empty string is also valid `""`.

**Comment by CKrawczyk** [comment]
I think the root cause of the issue is the data type auto-detection when reading in the csv file is detecting the `"text"` value as all numbers, and is assuming the data is an `int` instead of treating it as a `str`.

@mclenard What is your project's ID?  I will take a close look at the data export and see if I can make the type auto-detection work as expected.

**Comment by mclenard** [comment]
Thanks for the prompt response. Our project is #9524, the Tar Pits Zooniverse Project. I anticipated that doing something like adding quotes was a potential solution, so after I posted this I used GREL in openrefine to add some to the data and the reduction does indeed work fine. Alternatively, we could ask the participants to enter it that way. If that is what we need to do, that's totally workable - just one additional step in the workflow or a short instruction. But if you are willing to look into the auto-detection, that may also be helpful. Thanks again.

**Comment by CKrawczyk** [comment]
Thanks for confirming that adding quotes is the solution.

I will work on fixing this in the auto-detection.  Note to self: changing https://github.com/zooniverse/aggregation-for-caesar/blob/master/panoptes_aggregation/reducers/text_reducer.py#L18 to
```python
return [str(d['text']) for d in data_list if str(d['text']).strip() != '']
```
will likely fix it.
