### ISSUE TITLE
Add a consensus reducer

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/aggregation-for-caesar#277]
The often-used consensus reducer for Caesar would be a nice addition for folks to be able to use for offline analysis.  I acknowledge it seems a shame to duplicate code, but I don't think there's any way to leverage the existing Ruby code to help here directly.

**Comment by CKrawczyk** [comment]
In words what does the consensus reducer do?  What values does it return?

**Comment by lcjohnso** [comment]
Hi @CKrawczyk --

I'm thinking the consensus reducer should be a clone of what's currently available for Caesar: return the survey / question option with the most votes.

Outputs:
- `most_likely` = option with greatest number of classifications/votes
- `num_votes` = vote count for mostly likely option
- `agreement` = fraction of total votes held by most likely option.

**Comment by lcjohnso** [comment]
Perhaps the reducer code could even be a Python port of the Caesar model:
https://github.com/zooniverse/caesar/blob/master/app/models/reducers/consensus_reducer.rb

**Comment by lcjohnso** [comment]
Closed by #453
