### ISSUE TITLE
Exception looking for "version" column

### ISSUE THREAD

**Issue by rgov** [zooniverse/aggregation-for-caesar#314]
I am trying to use the `panoptes_aggregation` module I've just installed from PyPI to process a CSV file a collaborator has received from Zooniverse. The command I'm running is:

    panoptes_aggregation config classifications_march2020_rawdata.csv 12369

However, it quickly fails:

    File ".venv/lib/python3.6/site-packages/panoptes_aggregation/scripts/config_workflow_panoptes.py", line 41, in config_workflow
        wdx &= (workflows.version == version)
    File ".venv/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
        return object.__getattribute__(self, name)
    AttributeError: 'DataFrame' object has no attribute 'version'

Indeed if I look at the columns in the `workflows` data frame, I see:

    ['classification_id', 'user_name', 'user_id', 'user_ip', 'workflow_id', 'workflow_name',
     'workflow_version', 'created_at', 'gold_standard', 'expert', 'metadata', 'annotations', 
     'subject_data', 'subject_ids']

I am guessing `workflow_version` is something like `{version}.{minor_version}` and it wouldn't be too hard to work around this, but since the schema of this document doesn't match what the scripts expect, it seems likely I'll encounter more issues.

How should I proceed?

**Comment by CKrawczyk** [comment]
For the `config` stage you need us the `workflow` data dump from the project builder.  The `classification` data dump (what you are using above) is passed into the `extract` step.

![Screen Shot 2020-06-01 at 9 37 42 AM](https://user-images.githubusercontent.com/6557526/83391693-c1114d00-a3eb-11ea-8c6c-e81787680332.png)
