### ISSUE TITLE
Add a new attribute to the reduction text blob

### ISSUE THREAD

**Issue by wgranger** [zooniverse/aggregation-for-caesar#322]
For ALICE, users need the ability to add a `flagged` boolean to each line. Currently, users can do this by pressing a flag icon on each line to add this attribute.

However, we discussed auto-populating this attribute, so a user seeing a transcription for the first time would automatically see the flags on all lines with a `low_consensus`. One important note here is that users should be able to toggle the `flagged` attribute, but users should not change the `low_consensus` value that arrives from Caesar.

We should add a `flagged` (bool) attribute to each transcription line that is auto-populated with the `low_consensus` boolean. This would allow us to toggle that value without having to touch the read-only nature of `low_consensus`

For reference, [here](https://docs.google.com/document/d/1gG-1jnSvRN6gUWwLNv6TJxM-ujN5hupTGaWuxNQ70R4/edit#heading=h.d55ws0ia3xy) is the API documentation where you can find the location of the `low_consensus` attribute

**Comment by CKrawczyk** [comment]
This update has been merged in.  Any current subjects in Alice will be auto flagged if they are re-aggregated.
