### ISSUE TITLE
#filter_annotations() missing key for line_text_extractor

### ISSUE THREAD

**Issue by simensta** [zooniverse/aggregation-for-caesar#61]
While running `extract_panoptes_csv.py` offline on line-by-line transcription data from Panoptes, I ran into the following error on [line 11 in `filter_annotations.py`](https://github.com/zooniverse/aggregation-for-caesar/blob/master/panoptes_aggregation/extractors/filter_annotations.py#L11):
```
if len(tool_config['details']) > 0:
KeyError: 'details'
```

**Comment by CKrawczyk** [comment]
What project/workflow did this crash on?  I think I know what is happening, but I want to do some test locally.

**Comment by simensta** [comment]
I was running data from DCW (project id: 2125, workflow id: 1874, min workflow version: 49).

**Comment by CKrawczyk** [comment]
OK, I have tracked down the error.  As a side note, there are some classifications that have identical positions for both the start and end points of the line.  I have no idea how this could happen since the front-end should not allow those to be created in the first place...
