### ISSUE TITLE
Change "line_text_reducer" to "poly_line_text_reducer" in extractor export?

### ISSUE THREAD

**Issue by simensta** [zooniverse/aggregation-for-caesar#64]
For context, I am running extractors and reducers on DCW (project id: 2125, workflow id: 1874, min workflow version: 49) to produce transcription aggregation results.

Running the `reduce_panoptes_csv.py` script, resulted in `KeyError: 'line_text_reducer'` for [line 91](https://github.com/zooniverse/aggregation-for-caesar/blob/master/bin/reduce_panoptes_csv.py#L91). In the extractor results, the column labeled extractor contains the value "line_text_extractor". If I change that value to "poly_line_text_extractor", the reducer script runs without errors.

I am not sure if this is a bug or an issue with how I am running the extractor and reducer scripts.

**Comment by CKrawczyk** [comment]
This is a bug, forgot to add 'line_text_reducer' to [this if block](https://github.com/zooniverse/aggregation-for-caesar/blob/master/bin/reduce_panoptes_csv.py#L44).
